### PR TITLE
Return transaction info from SendV2 activity

### PR DESCRIPTION
**Pull request by Alexandr1992**
According to the issue https://github.com/O3Labs/O3Android/issues/303 
Added setResult with transaction info to SendV2 activity

### CODE REVIEW

**Comment by saltyskip** [comment]
nice one 👍 

will review and merge it in once I finalize this PR 

https://github.com/O3Labs/O3Android/pull/305

**Comment by Alexandr1992** [comment]
> nice one 👍
> 
> will review and merge it in once I finalize this PR
> 
> #305

thank you

**Comment by Alexandr1992** [comment]
Hi, @saltyskip 
We see you have a lot of work on the current task. Maybe you hava any information about approximate plans or estimates for completing this task?
Any information would be very helpful for us.
Thank you)

**Comment by saltyskip** [comment]
@Alexandr1992  Tested and LGTM, im starting to prep the new version for release should be on the play store within a day or so

Please keep me updated on the status of your app would love to see how the integration works when you release :)

**Pull request merged**
